#!/bin/bash
#
# Build a sysbench RPM.  The rpmdevtools package is required.

# The distro we are building for.  Common usage in the Red Hat world is elN for
# Enterprise Linux, where N is 5, 6, or 7.  Change this if building for others. 
DIST=el5

# Source info
VERSION=0.5
REVISION=2
SOURCE=sysbench-$VERSION
SOURCE_TAR=$SOURCE.tar.gz

# Package info
# Default location of RPM build directory when using rpmdev-setuptree
RPMBUILD=~/rpmbuild
# Base name for all RPM package files
PKG=$SOURCE-$REVISION.$DIST

function cleanup {
    rm -f $SOURCE_TAR
    rm -rf /tmp/$SOURCE
}

# Create ~/rpmbuild tree.  If it's there already, nothing to do.  Don't wipe it.
rpmdev-setuptree || {
    echo "Error setting up RPM build tree. Is the rpmdevtools package installed?"
    exit 1
}

echo "check/install required build packages..."
PACKAGES="epel-release rpmdevtools automake libtool"
pkglist=""
for p in $PACKAGES; do
    rpm -q --quiet $p || pkglist="$pkglist $p"
done
[ -n "$pkglist" ] && sudo yum install -y $pkglist

echo "create source tar file..." 
cleanup 
mkdir /tmp/$SOURCE
cp -r * /tmp/$SOURCE
tar -C /tmp -c -z -f $SOURCE_TAR $SOURCE
cp $SOURCE_TAR $RPMBUILD/SOURCES

echo "build RPMs..."
rpmbuild -ba \
    --define "dist $DIST" \
    --define "revision $REVISION" \
    rpm/sysbench.spec > build.log 2>&1

if [ $? -ne 0 ]; then
    echo "Build failed.  See build.log for details."
else
    echo "cleaning up and copying RPMs to dist..."
    rm -rf dist && mkdir -p dist
    cp -r $RPMBUILD/RPMS/$(uname -m)/$PKG.* dist
    cp $RPMBUILD/SRPMS/$PKG.* dist
    cleanup
fi

# Done
echo "Complete."

